# Generated by Django 3.1.4 on 2020-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inventory',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='ingredients.Ingredient'),
        ),
    ]
