stages:
  - test
  - production

test:
  stage: test
  image: python:3.8
  script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - pip install pipenv
    - pipenv install
    - pipenv run python manage.py test

production:
  type: deploy
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master