before_script:
    - python -m pip install --upgrade pip
    - pip install pipenv
    - pipenv install

stages:
  - test
  - production

test:
  stage: test
  script:
    - pipenv run python manage.py test

production:
  type: deploy
  stage: production
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master