# Generated by Django 3.1.4 on 2020-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alocholic',
            field=models.BooleanField(default=True),
        ),
    ]
