# Generated by Django 3.1.4 on 2020-12-29 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_alocholic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='alocholic',
            new_name='alcoholic',
        ),
    ]
