# Generated by Django 3.1.4 on 2020-12-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='alocholic',
            new_name='alcoholic',
        ),
    ]
